### ISSUE TITLE
No merges in awhile

### ISSUE THREAD

**Issue by EHLOVader** [lkwdwrd/generator-vvv#48]
I wondered if you were actively working on this. I saw a bump in version recently but didn't know why.

I have two pull requests pending review and merges. #38 and #46

Also, #42 which is also pending a merge is now in conflict having sat for this long.

**Comment by lkwdwrd** [comment]
Yes, I've been working on a new version of this project, and plan to release it relatively soon as a full version 1. It is going to work slightly differently than the way it did before, and many of the ideas require some breaking changes. This will include the name and format of the JSON file.

The overall idea is exactly the same, this tool will allow you to define sharable projects and allow you to set up complex websites using VVV as the landing area. However, the lessons learned in this version of the generator are being taken heavily into consideration. This current version doesn't offer enough flexibility in setup style or requirements - so the goal of version 1 is to open things up even further while using smart defaults to push forward thoughts and idea I have on best practices.

As soon as it's in a state that can be tested, I will push the new version.

I'm happy to merge your PRs in the meantime, but v1 will be pretty much a complete rewrite to take this from something I threw together in a few weeks to a project that can be better maintained, is more flexible, and is more extensible that what it is today.

**Comment by EHLOVader** [comment]
Awesome, thanks for the quick reply. I will watch for the new release. 

These can wait or be closed with wontfix if the main problems of each are solved in the new version. I have survived well enough in a branch of my fork where I was piling all of these together. I was just going through some of my own github PRs and issues and see if I can do anything to help make them happen.

**Comment by lkwdwrd** [comment]
@EHLOVader - I'm going to close this issue out. Would love for you to start testing the new version if you are interested. I have several members of my team testing it out to see how well it works in a shared environment. Check out the [version1 branch](https://github.com/lkwdwrd/generator-vvv/blob/version1/) and `$ npm link` it to give it a try. As soon as it's stable it will get pushed to NPM as 1.0.0
